# Scraping the performances of the top 100 test match run scorers from Cricinfo's Statsguru

As a way to practice my web scraping and D3 skills I've been meaning to do this for a while. There's no public API for Statsguru and it's not easy to grab a list of each player. The easiest way to get this is to scrape the summary table for batting and bowling then grab the player ID for each player in the top 100 from the links in the table. We can then use this ID to build the URL for the full performance list for each player and then use that to scrape the data and put it in a single file. Easy!

First, let's import `BeautifulSoup` and `requests` for scraping, and `pandas` for data munging....

In [44]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

In [110]:
summary_url = "http://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;orderby=runs;template=results;type=batting"

summary_r = requests.get(summary_url)
summary_soup = BeautifulSoup(summary_r.content, 'html5lib')
summary_table = summary_soup.find_all("table", class_="engineTable")[2].tbody

In [85]:
player_list = []

for row in summary_table.find_all('tr'):
    link = row.find_all('td')[0].find('a')
    
    player_name = link.contents[0]
    player_id = re.search('player\/(.+?)\.html', link['href']).group(1)
    
    temp_details = {}
    temp_details['name'] = player_name
    temp_details['id'] = player_id
    
    player_list.append(temp_details)

player_list

[{'id': '35320', 'name': 'SR Tendulkar'},
 {'id': '7133', 'name': 'RT Ponting'},
 {'id': '45789', 'name': 'JH Kallis'},
 {'id': '28114', 'name': 'R Dravid'},
 {'id': '50710', 'name': 'KC Sangakkara'},
 {'id': '52337', 'name': 'BC Lara'},
 {'id': '51469', 'name': 'S Chanderpaul'},
 {'id': '49289', 'name': 'DPMD Jayawardene'},
 {'id': '4174', 'name': 'AR Border'},
 {'id': '8192', 'name': 'SR Waugh'},
 {'id': '28794', 'name': 'SM Gavaskar'},
 {'id': '11728', 'name': 'AN Cook'},
 {'id': '47270', 'name': 'GC Smith'},
 {'id': '43652', 'name': 'Younis Khan'},
 {'id': '13399', 'name': 'GA Gooch'},
 {'id': '40879', 'name': 'Javed Miandad'},
 {'id': '40570', 'name': 'Inzamam-ul-Haq'},
 {'id': '30750', 'name': 'VVS Laxman'},
 {'id': '4578', 'name': 'MJ Clarke'},
 {'id': '5616', 'name': 'ML Hayden'},
 {'id': '35263', 'name': 'V Sehwag'},
 {'id': '52812', 'name': 'IVA Richards'},
 {'id': '20372', 'name': 'AJ Stewart'},
 {'id': '13418', 'name': 'DI Gower'},
 {'id': '19296', 'name': 'KP Pietersen'},
 {'id': '9187', 'name': 'G Boycott'},
 {'id': '44936', 'name': 'AB de Villiers'},
 {'id': '52946', 'name': 'GS Sobers'},
 {'id': '8189', 'name': 'ME Waugh'},
 {'id': '8579', 'name': 'MA Atherton'},
 {'id': '9062', 'name': 'IR Bell'},
 {'id': '6256', 'name': 'JL Langer'},
 {'id': '10846', 'name': 'MC Cowdrey'},
 {'id': '51901', 'name': 'CG Greenidge'},
 {'id': '43650', 'name': 'Mohammad Yousuf'},
 {'id': '7924', 'name': 'MA Taylor'},
 {'id': '52345', 'name': 'CH Lloyd'},
 {'id': '52047', 'name': 'DL Haynes'},
 {'id': '4169', 'name': 'DC Boon'},
 {'id': '45813', 'name': 'G Kirsten'},
 {'id': '43906', 'name': 'HM Amla'},
 {'id': '14022', 'name': 'WR Hammond'},
 {'id': '51880', 'name': 'CH Gayle'},
 {'id': '28779', 'name': 'SC Ganguly'},
 {'id': '37000', 'name': 'SP Fleming'},
 {'id': '4558', 'name': 'GS Chappell'},
 {'id': '20387', 'name': 'AJ Strauss'},
 {'id': '4188', 'name': 'DG Bradman'},
 {'id': '49209', 'name': 'ST Jayasuriya'},
 {'id': '14334', 'name': 'L Hutton'}]

In [86]:
player_id = player_list[0]['id']

innings_list_url = "http://stats.espncricinfo.com/ci/engine/player/" + player_id + ".html?class=1;orderby=runs;template=results;type=batting;view=innings"

player_r = requests.get(innings_list_url)
player_soup = BeautifulSoup(player_r.content, 'html5lib')
player_table = player_soup.find_all("table", class_="engineTable")[3].tbody
player_table

<tbody>
 <tr class="data1">
  <td class="padAst">15</td>
  <td>28</td>
  <td>24</td>
  <td>2</td>
  <td>0</td>
  <td>62.50</td>
  <td>6</td>
  <td>bowled</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/7.html">Pakistan</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/58956.html">Karachi</a></td>
  <td nowrap="nowrap"><b>15 Nov 1989</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63513.html" title="view the scorecard for this row">Test # 1127</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">DNB</td>
  <td nowrap="nowrap">-</td>
  <td nowrap="nowrap">-</td>
  <td nowrap="nowrap">-</td>
  <td nowrap="nowrap">-</td>
  <td class="padDp2" nowrap="nowrap">-</td>
  <td nowrap="nowrap">-</td>
  <td nowrap="nowrap">-</td>
  <td>4</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/7.html">Pakistan</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/58956.html">Karachi</a></td>
  <td nowrap="nowrap"><b>15 Nov 1989</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63513.html" title="view the scorecard for this row">Test # 1127</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">59</td>
  <td>254</td>
  <td>172</td>
  <td>4</td>
  <td>0</td>
  <td>34.30</td>
  <td>6</td>
  <td>lbw</td>
  <td>1</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/7.html">Pakistan</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/58927.html">Faisalabad</a></td>
  <td nowrap="nowrap"><b>23 Nov 1989</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63514.html" title="view the scorecard for this row">Test # 1128</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">8</td>
  <td>24</td>
  <td>16</td>
  <td>1</td>
  <td>0</td>
  <td>50.00</td>
  <td>6</td>
  <td nowrap="nowrap">run out</td>
  <td>3</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/7.html">Pakistan</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/58927.html">Faisalabad</a></td>
  <td nowrap="nowrap"><b>23 Nov 1989</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63514.html" title="view the scorecard for this row">Test # 1128</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">41</td>
  <td>124</td>
  <td>90</td>
  <td>5</td>
  <td>0</td>
  <td>45.55</td>
  <td>7</td>
  <td>bowled</td>
  <td>1</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/7.html">Pakistan</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/58967.html">Lahore</a></td>
  <td nowrap="nowrap"><b>1 Dec 1989</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63515.html" title="view the scorecard for this row">Test # 1130</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">35</td>
  <td>74</td>
  <td>51</td>
  <td>5</td>
  <td>0</td>
  <td>68.62</td>
  <td>6</td>
  <td>lbw</td>
  <td>1</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/7.html">Pakistan</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/59018.html">Sialkot</a></td>
  <td nowrap="nowrap"><b>9 Dec 1989</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63516.html" title="view the scorecard for this row">Test # 1132</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">57</td>
  <td>193</td>
  <td>134</td>
  <td>6</td>
  <td>0</td>
  <td>42.53</td>
  <td>6</td>
  <td>caught</td>
  <td>3</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/7.html">Pakistan</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/59018.html">Sialkot</a></td>
  <td nowrap="nowrap"><b>9 Dec 1989</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63516.html" title="view the scorecard for this row">Test # 1132</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">0</td>
  <td>1</td>
  <td>1</td>
  <td>0</td>
  <td>0</td>
  <td>0.00</td>
  <td>6</td>
  <td>caught</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/5.html">New Zealand</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/58812.html">Christchurch</a></td>
  <td nowrap="nowrap"><b>2 Feb 1990</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63523.html" title="view the scorecard for this row">Test # 1136</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">24</td>
  <td>50</td>
  <td>44</td>
  <td>3</td>
  <td>0</td>
  <td>54.54</td>
  <td>6</td>
  <td>caught</td>
  <td>3</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/5.html">New Zealand</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/58812.html">Christchurch</a></td>
  <td nowrap="nowrap"><b>2 Feb 1990</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63523.html" title="view the scorecard for this row">Test # 1136</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">88</td>
  <td>324</td>
  <td>266</td>
  <td>5</td>
  <td>0</td>
  <td>33.08</td>
  <td>6</td>
  <td>caught</td>
  <td>1</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/5.html">New Zealand</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/58857.html">Napier</a></td>
  <td nowrap="nowrap"><b>9 Feb 1990</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63524.html" title="view the scorecard for this row">Test # 1138</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">5</td>
  <td>15</td>
  <td>13</td>
  <td>1</td>
  <td>0</td>
  <td>38.46</td>
  <td>6</td>
  <td>caught</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/5.html">New Zealand</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/58792.html">Auckland</a></td>
  <td nowrap="nowrap"><b>22 Feb 1990</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63525.html" title="view the scorecard for this row">Test # 1139</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">DNB</td>
  <td nowrap="nowrap">-</td>
  <td nowrap="nowrap">-</td>
  <td nowrap="nowrap">-</td>
  <td nowrap="nowrap">-</td>
  <td class="padDp2" nowrap="nowrap">-</td>
  <td nowrap="nowrap">-</td>
  <td nowrap="nowrap">-</td>
  <td>4</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/5.html">New Zealand</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/58792.html">Auckland</a></td>
  <td nowrap="nowrap"><b>22 Feb 1990</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63525.html" title="view the scorecard for this row">Test # 1139</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">10</td>
  <td>30</td>
  <td>19</td>
  <td>1</td>
  <td>0</td>
  <td>52.63</td>
  <td>6</td>
  <td>bowled</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/1.html">England</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/57129.html">Lord's</a></td>
  <td nowrap="nowrap"><b>26 Jul 1990</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63534.html" title="view the scorecard for this row">Test # 1148</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">27</td>
  <td>93</td>
  <td>65</td>
  <td>4</td>
  <td>0</td>
  <td>41.53</td>
  <td>6</td>
  <td>caught</td>
  <td>4</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/1.html">England</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/57129.html">Lord's</a></td>
  <td nowrap="nowrap"><b>26 Jul 1990</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63534.html" title="view the scorecard for this row">Test # 1148</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">68</td>
  <td>216</td>
  <td>136</td>
  <td>8</td>
  <td>0</td>
  <td>50.00</td>
  <td>6</td>
  <td>caught</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/1.html">England</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/57160.html">Manchester</a></td>
  <td nowrap="nowrap"><b>9 Aug 1990</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63535.html" title="view the scorecard for this row">Test # 1149</a></td>
 </tr>
 <tr class="data1">
  <td>119*</td>
  <td>225</td>
  <td>189</td>
  <td>17</td>
  <td>0</td>
  <td>62.96</td>
  <td>6</td>
  <td nowrap="nowrap">not out</td>
  <td>4</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/1.html">England</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/57160.html">Manchester</a></td>
  <td nowrap="nowrap"><b>9 Aug 1990</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63535.html" title="view the scorecard for this row">Test # 1149</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">21</td>
  <td>39</td>
  <td>30</td>
  <td>3</td>
  <td>0</td>
  <td>70.00</td>
  <td>7</td>
  <td>caught</td>
  <td>1</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/1.html">England</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/57127.html">The Oval</a></td>
  <td nowrap="nowrap"><b>23 Aug 1990</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63536.html" title="view the scorecard for this row">Test # 1150</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">11</td>
  <td>92</td>
  <td nowrap="nowrap">-</td>
  <td nowrap="nowrap">-</td>
  <td>0</td>
  <td class="padDp2" nowrap="nowrap">-</td>
  <td>6</td>
  <td>lbw</td>
  <td>1</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/8.html">Sri Lanka</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/57993.html">Chandigarh</a></td>
  <td nowrap="nowrap"><b>23 Nov 1990</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63548.html" title="view the scorecard for this row">Test # 1156</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">16</td>
  <td>47</td>
  <td>42</td>
  <td>3</td>
  <td>0</td>
  <td>38.09</td>
  <td>6</td>
  <td>bowled</td>
  <td>1</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/2.html">Australia</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/56336.html">Brisbane</a></td>
  <td nowrap="nowrap"><b>29 Nov 1991</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63563.html" title="view the scorecard for this row">Test # 1177</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">7</td>
  <td>36</td>
  <td>25</td>
  <td>1</td>
  <td>0</td>
  <td>28.00</td>
  <td>6</td>
  <td>caught</td>
  <td>3</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/2.html">Australia</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/56336.html">Brisbane</a></td>
  <td nowrap="nowrap"><b>29 Nov 1991</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63563.html" title="view the scorecard for this row">Test # 1177</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">15</td>
  <td>33</td>
  <td>23</td>
  <td>0</td>
  <td>0</td>
  <td>65.21</td>
  <td>7</td>
  <td>caught</td>
  <td>1</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/2.html">Australia</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/56441.html">Melbourne</a></td>
  <td nowrap="nowrap"><b>26 Dec 1991</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63564.html" title="view the scorecard for this row">Test # 1180</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">40</td>
  <td>122</td>
  <td>107</td>
  <td>5</td>
  <td>0</td>
  <td>37.38</td>
  <td>7</td>
  <td>caught</td>
  <td>3</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/2.html">Australia</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/56441.html">Melbourne</a></td>
  <td nowrap="nowrap"><b>26 Dec 1991</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63564.html" title="view the scorecard for this row">Test # 1180</a></td>
 </tr>
 <tr class="data1">
  <td>148*</td>
  <td>298</td>
  <td>213</td>
  <td>14</td>
  <td>0</td>
  <td>69.48</td>
  <td>6</td>
  <td nowrap="nowrap">not out</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/2.html">Australia</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/56544.html">Sydney</a></td>
  <td nowrap="nowrap"><b>2 Jan 1992</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63565.html" title="view the scorecard for this row">Test # 1181</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">6</td>
  <td>20</td>
  <td>8</td>
  <td>1</td>
  <td>0</td>
  <td>75.00</td>
  <td>6</td>
  <td>lbw</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/2.html">Australia</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/56293.html">Adelaide</a></td>
  <td nowrap="nowrap"><b>25 Jan 1992</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63566.html" title="view the scorecard for this row">Test # 1184</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">17</td>
  <td>36</td>
  <td>29</td>
  <td>2</td>
  <td>0</td>
  <td>58.62</td>
  <td>4</td>
  <td>lbw</td>
  <td>4</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/2.html">Australia</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/56293.html">Adelaide</a></td>
  <td nowrap="nowrap"><b>25 Jan 1992</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63566.html" title="view the scorecard for this row">Test # 1184</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">114</td>
  <td>228</td>
  <td>161</td>
  <td>16</td>
  <td>0</td>
  <td>70.80</td>
  <td>4</td>
  <td>caught</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/2.html">Australia</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/56490.html">Perth</a></td>
  <td nowrap="nowrap"><b>1 Feb 1992</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63567.html" title="view the scorecard for this row">Test # 1186</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">5</td>
  <td>12</td>
  <td>9</td>
  <td>1</td>
  <td>0</td>
  <td>55.55</td>
  <td>4</td>
  <td>caught</td>
  <td>4</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/2.html">Australia</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/56490.html">Perth</a></td>
  <td nowrap="nowrap"><b>1 Feb 1992</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63567.html" title="view the scorecard for this row">Test # 1186</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">0</td>
  <td>4</td>
  <td>3</td>
  <td>0</td>
  <td>0</td>
  <td>0.00</td>
  <td>4</td>
  <td>caught</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/9.html">Zimbabwe</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/59545.html">Harare</a></td>
  <td nowrap="nowrap"><b>18 Oct 1992</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63583.html" title="view the scorecard for this row">Test # 1197</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">11</td>
  <td>35</td>
  <td>24</td>
  <td>1</td>
  <td>0</td>
  <td>45.83</td>
  <td>4</td>
  <td nowrap="nowrap">run out</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/3.html">South Africa</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/59089.html">Durban</a></td>
  <td nowrap="nowrap"><b>13 Nov 1992</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63586.html" title="view the scorecard for this row">Test # 1200</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">111</td>
  <td>373</td>
  <td>270</td>
  <td>19</td>
  <td>0</td>
  <td>41.11</td>
  <td>4</td>
  <td>caught</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/3.html">South Africa</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/59120.html">Johannesburg</a></td>
  <td nowrap="nowrap"><b>26 Nov 1992</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63587.html" title="view the scorecard for this row">Test # 1201</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">1</td>
  <td>6</td>
  <td>5</td>
  <td>0</td>
  <td>0</td>
  <td>20.00</td>
  <td>4</td>
  <td>lbw</td>
  <td>4</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/3.html">South Africa</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/59120.html">Johannesburg</a></td>
  <td nowrap="nowrap"><b>26 Nov 1992</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63587.html" title="view the scorecard for this row">Test # 1201</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">6</td>
  <td>27</td>
  <td>17</td>
  <td>1</td>
  <td>0</td>
  <td>35.29</td>
  <td>4</td>
  <td>caught</td>
  <td>1</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/3.html">South Africa</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/59159.html">Port Elizabeth</a></td>
  <td nowrap="nowrap"><b>26 Dec 1992</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63588.html" title="view the scorecard for this row">Test # 1206</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">0</td>
  <td>1</td>
  <td>1</td>
  <td>0</td>
  <td>0</td>
  <td>0.00</td>
  <td>4</td>
  <td>caught</td>
  <td>3</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/3.html">South Africa</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/59159.html">Port Elizabeth</a></td>
  <td nowrap="nowrap"><b>26 Dec 1992</b></td>
  <td style="white-space: nowrap;"><a href="/ci/engine/match/63588.html" title="view the scorecard for this row">Test # 1206</a></td>
 </tr>
 <tr class="data1">
  <td class="padAst">73</td>
  <td>272</td>
  <td>208</td>
  <td>8</td>
  <td>1</td>
  <td>35.09</td>
  <td>5</td>
  <td>caught</td>
  <td>2</td>
  <td></td>
  <td class="left" nowrap="nowrap">v <a class="data-link" href="/ci/content/team/3.html">South Africa</a></td>
  <td class="left" nowrap="nowrap"><a class="data-link" href="/ci/content/ground/59068.html">Cape Town</a></td>
  <td nowrap="nowrap"><b>2 Jan 1993</b></td>

In [108]:
innings_list = []
cumulative_runs = 0

for row in player_table.findAll('tr'):
    cells = row.find_all('td')

    if cells[0].string != 'DNB' and cells[0].string != 'TDNB':
        innings = {}
        cumulative_runs += int(re.sub('\*', '', cells[0].string))
        
        innings['cum_runs'] = cumulative_runs
        innings['runs'] = int(re.sub('\*', '', cells[0].string))
        innings['mins'] = int(cells[1].string)
        innings['balls'] = int(cells[2].string)
        innings['fours'] = int(cells[3].string)
        innings['sixes'] = int(cells[4].string)
        innings['strike_rate'] = cells[5].string
        innings['position'] = cells[6].string
        innings['how_out'] = cells[7].string
        innings['innings'] = cells[8].string
        innings['opponent'] = cells[10].find('a').contents[0]
        innings['venue'] = cells[11].find('a').contents[0]
        innings['date'] = cells[12].string

        innings_list.append(innings)

innings_list

[{'balls': '24',
  'cum_runs': 15,
  'date': '15 Nov 1989',
  'fours': '2',
  'how_out': 'bowled',
  'innings': '2',
  'mins': '28',
  'opponent': 'Pakistan',
  'position': '6',
  'runs': '15',
  'sixes': '0',
  'strike_rate': '62.50',
  'venue': 'Karachi'},
 {'balls': '172',
  'cum_runs': 74,
  'date': '23 Nov 1989',
  'fours': '4',
  'how_out': 'lbw',
  'innings': '1',
  'mins': '254',
  'opponent': 'Pakistan',
  'position': '6',
  'runs': '59',
  'sixes': '0',
  'strike_rate': '34.30',
  'venue': 'Faisalabad'},
 {'balls': '16',
  'cum_runs': 82,
  'date': '23 Nov 1989',
  'fours': '1',
  'how_out': 'run out',
  'innings': '3',
  'mins': '24',
  'opponent': 'Pakistan',
  'position': '6',
  'runs': '8',
  'sixes': '0',
  'strike_rate': '50.00',
  'venue': 'Faisalabad'},
 {'balls': '90',
  'cum_runs': 123,
  'date': '1 Dec 1989',
  'fours': '5',
  'how_out': 'bowled',
  'innings': '1',
  'mins': '124',
  'opponent': 'Pakistan',
  'position': '7',
  'runs': '41',
  'sixes': '0',
  'strike_rate': '45.55',
  'venue': 'Lahore'},
 {'balls': '51',
  'cum_runs': 158,
  'date': '9 Dec 1989',
  'fours': '5',
  'how_out': 'lbw',
  'innings': '1',
  'mins': '74',
  'opponent': 'Pakistan',
  'position': '6',
  'runs': '35',
  'sixes': '0',
  'strike_rate': '68.62',
  'venue': 'Sialkot'},
 {'balls': '134',
  'cum_runs': 215,
  'date': '9 Dec 1989',
  'fours': '6',
  'how_out': 'caught',
  'innings': '3',
  'mins': '193',
  'opponent': 'Pakistan',
  'position': '6',
  'runs': '57',
  'sixes': '0',
  'strike_rate': '42.53',
  'venue': 'Sialkot'},
 {'balls': '1',
  'cum_runs': 215,
  'date': '2 Feb 1990',
  'fours': '0',
  'how_out': 'caught',
  'innings': '2',
  'mins': '1',
  'opponent': 'New Zealand',
  'position': '6',
  'runs': '0',
  'sixes': '0',
  'strike_rate': '0.00',
  'venue': 'Christchurch'},
 {'balls': '44',
  'cum_runs': 239,
  'date': '2 Feb 1990',
  'fours': '3',
  'how_out': 'caught',
  'innings': '3',
  'mins': '50',
  'opponent': 'New Zealand',
  'position': '6',
  'runs': '24',
  'sixes': '0',
  'strike_rate': '54.54',
  'venue': 'Christchurch'},
 {'balls': '266',
  'cum_runs': 327,
  'date': '9 Feb 1990',
  'fours': '5',
  'how_out': 'caught',
  'innings': '1',
  'mins': '324',
  'opponent': 'New Zealand',
  'position': '6',
  'runs': '88',
  'sixes': '0',
  'strike_rate': '33.08',
  'venue': 'Napier'},
 {'balls': '13',
  'cum_runs': 332,
  'date': '22 Feb 1990',
  'fours': '1',
  'how_out': 'caught',
  'innings': '2',
  'mins': '15',
  'opponent': 'New Zealand',
  'position': '6',
  'runs': '5',
  'sixes': '0',
  'strike_rate': '38.46',
  'venue': 'Auckland'},
 {'balls': '19',
  'cum_runs': 342,
  'date': '26 Jul 1990',
  'fours': '1',
  'how_out': 'bowled',
  'innings': '2',
  'mins': '30',
  'opponent': 'England',
  'position': '6',
  'runs': '10',
  'sixes': '0',
  'strike_rate': '52.63',
  'venue': "Lord's"},
 {'balls': '65',
  'cum_runs': 369,
  'date': '26 Jul 1990',
  'fours': '4',
  'how_out': 'caught',
  'innings': '4',
  'mins': '93',
  'opponent': 'England',
  'position': '6',
  'runs': '27',
  'sixes': '0',
  'strike_rate': '41.53',
  'venue': "Lord's"},
 {'balls': '136',
  'cum_runs': 437,
  'date': '9 Aug 1990',
  'fours': '8',
  'how_out': 'caught',
  'innings': '2',
  'mins': '216',
  'opponent': 'England',
  'position': '6',
  'runs': '68',
  'sixes': '0',
  'strike_rate': '50.00',
  'venue': 'Manchester'},
 {'balls': '189',
  'cum_runs': 556,
  'date': '9 Aug 1990',
  'fours': '17',
  'how_out': 'not out',
  'innings': '4',
  'mins': '225',
  'opponent': 'England',
  'position': '6',
  'runs': '119',
  'sixes': '0',
  'strike_rate': '62.96',
  'venue': 'Manchester'},
 {'balls': '30',
  'cum_runs': 577,
  'date': '23 Aug 1990',
  'fours': '3',
  'how_out': 'caught',
  'innings': '1',
  'mins': '39',
  'opponent': 'England',
  'position': '7',
  'runs': '21',
  'sixes': '0',
  'strike_rate': '70.00',
  'venue': 'The Oval'},
 {'balls': '-',
  'cum_runs': 588,
  'date': '23 Nov 1990',
  'fours': '-',
  'how_out': 'lbw',
  'innings': '1',
  'mins': '92',
  'opponent': 'Sri Lanka',
  'position': '6',
  'runs': '11',
  'sixes': '0',
  'strike_rate': '-',
  'venue': 'Chandigarh'},
 {'balls': '42',
  'cum_runs': 604,
  'date': '29 Nov 1991',
  'fours': '3',
  'how_out': 'bowled',
  'innings': '1',
  'mins': '47',
  'opponent': 'Australia',
  'position': '6',
  'runs': '16',
  'sixes': '0',
  'strike_rate': '38.09',
  'venue': 'Brisbane'},
 {'balls': '25',
  'cum_runs': 611,
  'date': '29 Nov 1991',
  'fours': '1',
  'how_out': 'caught',
  'innings': '3',
  'mins': '36',
  'opponent': 'Australia',
  'position': '6',
  'runs': '7',
  'sixes': '0',
  'strike_rate': '28.00',
  'venue': 'Brisbane'},
 {'balls': '23',
  'cum_runs': 626,
  'date': '26 Dec 1991',
  'fours': '0',
  'how_out': 'caught',
  'innings': '1',
  'mins': '33',
  'opponent': 'Australia',
  'position': '7',
  'runs': '15',
  'sixes': '0',
  'strike_rate': '65.21',
  'venue': 'Melbourne'},
 {'balls': '107',
  'cum_runs': 666,
  'date': '26 Dec 1991',
  'fours': '5',
  'how_out': 'caught',
  'innings': '3',
  'mins': '122',
  'opponent': 'Australia',
  'position': '7',
  'runs': '40',
  'sixes': '0',
  'strike_rate': '37.38',
  'venue': 'Melbourne'},
 {'balls': '213',
  'cum_runs': 814,
  'date': '2 Jan 1992',
  'fours': '14',
  'how_out': 'not out',
  'innings': '2',
  'mins': '298',
  'opponent': 'Australia',
  'position': '6',
  'runs': '148',
  'sixes': '0',
  'strike_rate': '69.48',
  'venue': 'Sydney'},
 {'balls': '8',
  'cum_runs': 820,
  'date': '25 Jan 1992',
  'fours': '1',
  'how_out': 'lbw',
  'innings': '2',
  'mins': '20',
  'opponent': 'Australia',
  'position': '6',
  'runs': '6',
  'sixes': '0',
  'strike_rate': '75.00',
  'venue': 'Adelaide'},
 {'balls': '29',
  'cum_runs': 837,
  'date': '25 Jan 1992',
  'fours': '2',
  'how_out': 'lbw',
  'innings': '4',
  'mins': '36',
  'opponent': 'Australia',
  'position': '4',
  'runs': '17',
  'sixes': '0',
  'strike_rate': '58.62',
  'venue': 'Adelaide'},
 {'balls': '161',
  'cum_runs': 951,
  'date': '1 Feb 1992',
  'fours': '16',
  'how_out': 'caught',
  'innings': '2',
  'mins': '228',
  'opponent': 'Australia',
  'position': '4',
  'runs': '114',
  'sixes': '0',
  'strike_rate': '70.80',
  'venue': 'Perth'},
 {'balls': '9',
  'cum_runs': 956,
  'date': '1 Feb 1992',
  'fours': '1',
  'how_out': 'caught',
  'innings': '4',
  'mins': '12',
  'opponent': 'Australia',
  'position': '4',
  'runs': '5',
  'sixes': '0',
  'strike_rate': '55.55',
  'venue': 'Perth'},
 {'balls': '3',
  'cum_runs': 956,
  'date': '18 Oct 1992',
  'fours': '0',
  'how_out': 'caught',
  'innings': '2',
  'mins': '4',
  'opponent': 'Zimbabwe',
  'position': '4',
  'runs': '0',
  'sixes': '0',
  'strike_rate': '0.00',
  'venue': 'Harare'},
 {'balls': '24',
  'cum_runs': 967,
  'date': '13 Nov 1992',
  'fours': '1',
  'how_out': 'run out',
  'innings': '2',
  'mins': '35',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '11',
  'sixes': '0',
  'strike_rate': '45.83',
  'venue': 'Durban'},
 {'balls': '270',
  'cum_runs': 1078,
  'date': '26 Nov 1992',
  'fours': '19',
  'how_out': 'caught',
  'innings': '2',
  'mins': '373',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '111',
  'sixes': '0',
  'strike_rate': '41.11',
  'venue': 'Johannesburg'},
 {'balls': '5',
  'cum_runs': 1079,
  'date': '26 Nov 1992',
  'fours': '0',
  'how_out': 'lbw',
  'innings': '4',
  'mins': '6',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '1',
  'sixes': '0',
  'strike_rate': '20.00',
  'venue': 'Johannesburg'},
 {'balls': '17',
  'cum_runs': 1085,
  'date': '26 Dec 1992',
  'fours': '1',
  'how_out': 'caught',
  'innings': '1',
  'mins': '27',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '6',
  'sixes': '0',
  'strike_rate': '35.29',
  'venue': 'Port Elizabeth'},
 {'balls': '1',
  'cum_runs': 1085,
  'date': '26 Dec 1992',
  'fours': '0',
  'how_out': 'caught',
  'innings': '3',
  'mins': '1',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '0',
  'sixes': '0',
  'strike_rate': '0.00',
  'venue': 'Port Elizabeth'},
 {'balls': '208',
  'cum_runs': 1158,
  'date': '2 Jan 1993',
  'fours': '8',
  'how_out': 'caught',
  'innings': '2',
  'mins': '272',
  'opponent': 'South Africa',
  'position': '5',
  'runs': '73',
  'sixes': '1',
  'strike_rate': '35.09',
  'venue': 'Cape Town'},
 {'balls': '118',
  'cum_runs': 1208,
  'date': '29 Jan 1993',
  'fours': '6',
  'how_out': 'caught',
  'innings': '1',
  'mins': '158',
  'opponent': 'England',
  'position': '4',
  'runs': '50',
  'sixes': '0',
  'strike_rate': '42.37',
  'venue': 'Kolkata'},
 {'balls': '19',
  'cum_runs': 1217,
  'date': '29 Jan 1993',
  'fours': '2',
  'how_out': 'not out',
  'innings': '4',
  'mins': '17',
  'opponent': 'England',
  'position': '4',
  'runs': '9',
  'sixes': '0',
  'strike_rate': '47.36',
  'venue': 'Kolkata'},
 {'balls': '296',
  'cum_runs': 1382,
  'date': '11 Feb 1993',
  'fours': '24',
  'how_out': 'caught',
  'innings': '1',
  'mins': '361',
  'opponent': 'England',
  'position': '4',
  'runs': '165',
  'sixes': '1',
  'strike_rate': '55.74',
  'venue': 'Chennai'},
 {'balls': '213',
  'cum_runs': 1460,
  'date': '19 Feb 1993',
  'fours': '10',
  'how_out': 'lbw',
  'innings': '2',
  'mins': '285',
  'opponent': 'England',
  'position': '4',
  'runs': '78',
  'sixes': '0',
  'strike_rate': '36.61',
  'venue': 'Mumbai'},
 {'balls': '114',
  'cum_runs': 1522,
  'date': '13 Mar 1993',
  'fours': '7',
  'how_out': 'caught',
  'innings': '1',
  'mins': '128',
  'opponent': 'Zimbabwe',
  'position': '4',
  'runs': '62',
  'sixes': '0',
  'strike_rate': '54.38',
  'venue': 'Delhi'},
 {'balls': '52',
  'cum_runs': 1550,
  'date': '27 Jul 1993',
  'fours': '5',
  'how_out': 'caught',
  'innings': '1',
  'mins': '74',
  'opponent': 'Sri Lanka',
  'position': '4',
  'runs': '28',
  'sixes': '0',
  'strike_rate': '53.84',
  'venue': 'Colombo (SSC)'},
 {'balls': '161',
  'cum_runs': 1654,
  'date': '27 Jul 1993',
  'fours': '11',
  'how_out': 'not out',
  'innings': '3',
  'mins': '217',
  'opponent': 'Sri Lanka',
  'position': '4',
  'runs': '104',
  'sixes': '1',
  'strike_rate': '64.59',
  'venue': 'Colombo (SSC)'},
 {'balls': '152',
  'cum_runs': 1725,
  'date': '4 Aug 1993',
  'fours': '10',
  'how_out': 'caught',
  'innings': '2',
  'mins': '202',
  'opponent': 'Sri Lanka',
  'position': '4',
  'runs': '71',
  'sixes': '0',
  'strike_rate': '46.71',
  'venue': 'Colombo (PSS)'},
 {'balls': '224',
  'cum_runs': 1867,
  'date': '18 Jan 1994',
  'fours': '22',
  'how_out': 'caught',
  'innings': '1',
  'mins': '260',
  'opponent': 'Sri Lanka',
  'position': '4',
  'runs': '142',
  'sixes': '0',
  'strike_rate': '63.39',
  'venue': 'Lucknow'},
 {'balls': '140',
  'cum_runs': 1963,
  'date': '26 Jan 1994',
  'fours': '15',
  'how_out': 'bowled',
  'innings': '1',
  'mins': '180',
  'opponent': 'Sri Lanka',
  'position': '4',
  'runs': '96',
  'sixes': '0',
  'strike_rate': '68.57',
  'venue': 'Bangalore'},
 {'balls': '14',
  'cum_runs': 1969,
  'date': '8 Feb 1994',
  'fours': '1',
  'how_out': 'bowled',
  'innings': '2',
  'mins': '25',
  'opponent': 'Sri Lanka',
  'position': '4',
  'runs': '6',
  'sixes': '0',
  'strike_rate': '42.85',
  'venue': 'Ahmedabad'},
 {'balls': '47',
  'cum_runs': 2012,
  'date': '19 Mar 1994',
  'fours': '7',
  'how_out': 'caught',
  'innings': '2',
  'mins': '55',
  'opponent': 'New Zealand',
  'position': '4',
  'runs': '43',
  'sixes': '0',
  'strike_rate': '91.48',
  'venue': 'Hamilton'},
 {'balls': '42',
  'cum_runs': 2023,
  'date': '19 Mar 1994',
  'fours': '0',
  'how_out': 'not out',
  'innings': '4',
  'mins': '57',
  'opponent': 'New Zealand',
  'position': '4',
  'runs': '11',
  'sixes': '0',
  'strike_rate': '26.19',
  'venue': 'Hamilton'},
 {'balls': '43',
  'cum_runs': 2057,
  'date': '18 Nov 1994',
  'fours': '7',
  'how_out': 'lbw',
  'innings': '1',
  'mins': '70',
  'opponent': 'West Indies',
  'position': '4',
  'runs': '34',
  'sixes': '0',
  'strike_rate': '79.06',
  'venue': 'Mumbai'},
 {'balls': '130',
  'cum_runs': 2142,
  'date': '18 Nov 1994',
  'fours': '10',
  'how_out': 'caught',
  'innings': '3',
  'mins': '178',
  'opponent': 'West Indies',
  'position': '5',
  'runs': '85',
  'sixes': '1',
  'strike_rate': '65.38',
  'venue': 'Mumbai'},
 {'balls': '322',
  'cum_runs': 2321,
  'date': '1 Dec 1994',
  'fours': '24',
  'how_out': 'caught',
  'innings': '1',
  'mins': '414',
  'opponent': 'West Indies',
  'position': '4',
  'runs': '179',
  'sixes': '1',
  'strike_rate': '55.59',
  'venue': 'Nagpur'},
 {'balls': '138',
  'cum_runs': 2375,
  'date': '1 Dec 1994',
  'fours': '3',
  'how_out': 'caught',
  'innings': '3',
  'mins': '180',
  'opponent': 'West Indies',
  'position': '4',
  'runs': '54',
  'sixes': '0',
  'strike_rate': '39.13',
  'venue': 'Nagpur'},
 {'balls': '55',
  'cum_runs': 2415,
  'date': '10 Dec 1994',
  'fours': '9',
  'how_out': 'caught',
  'innings': '2',
  'mins': '72',
  'opponent': 'West Indies',
  'position': '4',
  'runs': '40',
  'sixes': '0',
  'strike_rate': '72.72',
  'venue': 'Mohali'},
 {'balls': '24',
  'cum_runs': 2425,
  'date': '10 Dec 1994',
  'fours': '2',
  'how_out': 'caught',
  'innings': '4',
  'mins': '38',
  'opponent': 'West Indies',
  'position': '4',
  'runs': '10',
  'sixes': '0',
  'strike_rate': '41.66',
  'venue': 'Mohali'},
 {'balls': '4',
  'cum_runs': 2429,
  'date': '18 Oct 1995',
  'fours': '1',
  'how_out': 'caught',
  'innings': '2',
  'mins': '7',
  'opponent': 'New Zealand',
  'position': '4',
  'runs': '4',
  'sixes': '0',
  'strike_rate': '100.00',
  'venue': 'Bangalore'},
 {'balls': '0',
  'cum_runs': 2429,
  'date': '18 Oct 1995',
  'fours': '0',
  'how_out': 'not out',
  'innings': '4',
  'mins': '3',
  'opponent': 'New Zealand',
  'position': '4',
  'runs': '0',
  'sixes': '0',
  'strike_rate': '-',
  'venue': 'Bangalore'},
 {'balls': '88',
  'cum_runs': 2481,
  'date': '25 Oct 1995',
  'fours': '5',
  'how_out': 'not out',
  'innings': '1',
  'mins': '98',
  'opponent': 'New Zealand',
  'position': '4',
  'runs': '52',
  'sixes': '0',
  'strike_rate': '59.09',
  'venue': 'Chennai'},
 {'balls': '8',
  'cum_runs': 2483,
  'date': '8 Nov 1995',
  'fours': '0',
  'how_out': 'bowled',
  'innings': '1',
  'mins': '8',
  'opponent': 'New Zealand',
  'position': '4',
  'runs': '2',
  'sixes': '0',
  'strike_rate': '25.00',
  'venue': 'Cuttack'},
 {'balls': '41',
  'cum_runs': 2507,
  'date': '6 Jun 1996',
  'fours': '4',
  'how_out': 'bowled',
  'innings': '1',
  'mins': '71',
  'opponent': 'England',
  'position': '4',
  'runs': '24',
  'sixes': '0',
  'strike_rate': '58.53',
  'venue': 'Birmingham'},
 {'balls': '177',
  'cum_runs': 2629,
  'date': '6 Jun 1996',
  'fours': '19',
  'how_out': 'caught',
  'innings': '3',
  'mins': '263',
  'opponent': 'England',
  'position': '4',
  'runs': '122',
  'sixes': '1',
  'strike_rate': '68.92',
  'venue': 'Birmingham'},
 {'balls': '59',
  'cum_runs': 2660,
  'date': '20 Jun 1996',
  'fours': '5',
  'how_out': 'bowled',
  'innings': '2',
  'mins': '81',
  'opponent': 'England',
  'position': '4',
  'runs': '31',
  'sixes': '0',
  'strike_rate': '52.54',
  'venue': "Lord's"},
 {'balls': '360',
  'cum_runs': 2837,
  'date': '4 Jul 1996',
  'fours': '26',
  'how_out': 'caught',
  'innings': '1',
  'mins': '462',
  'opponent': 'England',
  'position': '4',
  'runs': '177',
  'sixes': '0',
  'strike_rate': '49.16',
  'venue': 'Nottingham'},
 {'balls': '97',
  'cum_runs': 2911,
  'date': '4 Jul 1996',
  'fours': '11',
  'how_out': 'caught',
  'innings': '3',
  'mins': '111',
  'opponent': 'England',
  'position': '4',
  'runs': '74',
  'sixes': '1',
  'strike_rate': '76.28',
  'venue': 'Nottingham'},
 {'balls': '11',
  'cum_runs': 2921,
  'date': '10 Oct 1996',
  'fours': '2',
  'how_out': 'caught',
  'innings': '2',
  'mins': '12',
  'opponent': 'Australia',
  'position': '4',
  'runs': '10',
  'sixes': '0',
  'strike_rate': '90.90',
  'venue': 'Delhi'},
 {'balls': '7',
  'cum_runs': 2921,
  'date': '10 Oct 1996',
  'fours': '0',
  'how_out': 'bowled',
  'innings': '4',
  'mins': '6',
  'opponent': 'Australia',
  'position': '4',
  'runs': '0',
  'sixes': '0',
  'strike_rate': '0.00',
  'venue': 'Delhi'},
 {'balls': '64',
  'cum_runs': 2963,
  'date': '20 Nov 1996',
  'fours': '7',
  'how_out': 'caught',
  'innings': '1',
  'mins': '80',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '42',
  'sixes': '0',
  'strike_rate': '65.62',
  'venue': 'Ahmedabad'},
 {'balls': '33',
  'cum_runs': 2970,
  'date': '20 Nov 1996',
  'fours': '1',
  'how_out': 'caught',
  'innings': '3',
  'mins': '43',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '7',
  'sixes': '0',
  'strike_rate': '21.21',
  'venue': 'Ahmedabad'},
 {'balls': '62',
  'cum_runs': 2988,
  'date': '27 Nov 1996',
  'fours': '3',
  'how_out': 'bowled',
  'innings': '2',
  'mins': '91',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '18',
  'sixes': '0',
  'strike_rate': '29.03',
  'venue': 'Kolkata'},
 {'balls': '25',
  'cum_runs': 2990,
  'date': '27 Nov 1996',
  'fours': '0',
  'how_out': 'caught',
  'innings': '4',
  'mins': '28',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '2',
  'sixes': '0',
  'strike_rate': '8.00',
  'venue': 'Kolkata'},
 {'balls': '173',
  'cum_runs': 3051,
  'date': '8 Dec 1996',
  'fours': '4',
  'how_out': 'caught',
  'innings': '1',
  'mins': '211',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '61',
  'sixes': '1',
  'strike_rate': '35.26',
  'venue': 'Kanpur'},
 {'balls': '98',
  'cum_runs': 3087,
  'date': '8 Dec 1996',
  'fours': '4',
  'how_out': 'caught',
  'innings': '3',
  'mins': '129',
  'opponent': 'South Africa',
  'position': '5',
  'runs': '36',
  'sixes': '0',
  'strike_rate': '36.73',
  'venue': 'Kanpur'},
 {'balls': '45',
  'cum_runs': 3102,
  'date': '26 Dec 1996',
  'fours': '2',
  'how_out': 'bowled',
  'innings': '2',
  'mins': '58',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '15',
  'sixes': '0',
  'strike_rate': '33.33',
  'venue': 'Durban'},
 {'balls': '25',
  'cum_runs': 3106,
  'date': '26 Dec 1996',
  'fours': '1',
  'how_out': 'caught',
  'innings': '4',
  'mins': '32',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '4',
  'sixes': '0',
  'strike_rate': '16.00',
  'venue': 'Durban'},
 {'balls': '254',
  'cum_runs': 3275,
  'date': '2 Jan 1997',
  'fours': '26',
  'how_out': 'caught',
  'innings': '2',
  'mins': '329',
  'opponent': 'South Africa',
  'position': '5',
  'runs': '169',
  'sixes': '0',
  'strike_rate': '66.53',
  'venue': 'Cape Town'},
 {'balls': '28',
  'cum_runs': 3284,
  'date': '2 Jan 1997',
  'fours': '1',
  'how_out': 'caught',
  'innings': '4',
  'mins': '38',
  'opponent': 'South Africa',
  'position': '5',
  'runs': '9',
  'sixes': '0',
  'strike_rate': '32.14',
  'venue': 'Cape Town'},
 {'balls': '55',
  'cum_runs': 3319,
  'date': '16 Jan 1997',
  'fours': '7',
  'how_out': 'caught',
  'innings': '1',
  'mins': '72',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '35',
  'sixes': '0',
  'strike_rate': '63.63',
  'venue': 'Johannesburg'},
 {'balls': '11',
  'cum_runs': 3328,
  'date': '16 Jan 1997',
  'fours': '2',
  'how_out': 'caught',
  'innings': '3',
  'mins': '13',
  'opponent': 'South Africa',
  'position': '4',
  'runs': '9',
  'sixes': '0',
  'strike_rate': '81.81',
  'venue': 'Johannesburg'},
 {'balls': '30',
  'cum_runs': 3335,
  'date': '6 Mar 1997',
  'fours': '1',
  'how_out': 'bowled',
  'innings': '2',
  'mins': '40',
  'opponent': 'West Indies',
  'position': '4',
  'runs': '7',
  'sixes': '0',
  'strike_rate': '23.33',
  'venue': 'Kingston'},
 {'balls': '36',
  'cum_runs': 3350,
  'date': '6 Mar 1997',
  'fours': '1',
  'how_out': 'not out',
  'innings': '4',
  'mins': '43',
  'opponent': 'West Indies',
  'position': '4',
  'runs': '15',
  'sixes': '0',
  'strike_rate': '41.66',

In [118]:
name_team = summary_table.find_all('tr')[0].find_all('td')[0].get_text()
re.search('\((.+?)\)', name_team).group(1)

'India'